apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17 #
  instances: 2
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-db-secrets
  storage:
    storageClass: longhorn
    size: 10Gi
  backup:
    volumeSnapshot:
      className: longhorn
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: n8n-store
        serverName: n8n-1
