---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vaultwarden-weekly-backup
spec:
  immediate: true
  schedule: "@weekly"
  backupOwnerReference: self
  cluster:
    name: vaultwarden-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vaultwarden-daily-snapshot
spec:
  immediate: true
  schedule: "@daily"
  backupOwnerReference: self
  cluster:
    name: vaultwarden-db
  method: volumeSnapshot
