apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:testing
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: vaultwarden-env
            - configMapRef:
                name: vaultwarden-domain
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-longhorn
