---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tailscale-controllers
  namespace: flux-system
resources:
  - secrets.yaml
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml

