apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 24h
  chart:
    spec:
      chart: tailscale-operator
      version: "1.90.9"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      interval: 24h
  values:
    operatorConfig:
      hostname: k3s
