apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:H+rvHU6JAY/f2l0nUytkdKw=,iv:aGON+9HKVTGl4H1sLqfueMaeCqUNOWDZXfip/i0cCVw=,tag:L1HFfzNw0yuRgggw27Zc3w==,type:str]
    client_secret: ENC[AES256_GCM,data:S2Tku9kf9KeMEG752Y/kmYCTicnJepk9yvrzhlk5799MmXArbyJNkavvh+O7bC4VDs3ROGySinitm90rEoWlVQ==,iv:/L7hpDJqoCDG3dTDOyVqzfcSCoMWY40Yh4EfiGC5q3A=,tag:0ylSgkjZgb4hkrqbixam1g==,type:str]
sops:
    age:
        - recipient: age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZamlOTkpKczJZSXJMZWhh
            Nzh1ZmtzQmVuL0RjYzlDS3gwSGVNQmhSK1EwCmw4dkZXckFLMlplYlhkVURYRzUw
            N1MwUE5KNUNoUmpYQk9zSFJrNnEvMDAKLS0tIFBkdVgvV1dqSjJoRkdDaTl5NlpJ
            bXdZR2lIa2RHU2prLy9lY1ZzQUxWM0UKJYF0J9s4zHcVw1SrGStmOR44I/uHcCpS
            420fIL0ipod6RH5H68xelqYo/a4+NSfXk7pxVZTf37W/xIER7mIs+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T12:14:50Z"
    mac: ENC[AES256_GCM,data:8JDrNgnhTxbPwAdh4Mo50vlraTAbFRYK45rdyS+bktKE1O4ebAxIoFqsl3SFnUGD+Ni1A+HLWnon8tUfQ89xwLPXGhJLzdJsyYXrj9DF7u3cbauPqiDsAyZdW21wIWgakQunzXiRrbk0PquNGmhpi4SJJkvHQxMVqtewi4CTafI=,iv:asomkGKQNRue2xOwoypfsQkrk6acsYXjUAY8iNpc3dA=,tag:2R6qVEokGg39EB0+RQ/P9A==,type:str]
    pgp:
        - created_at: "2025-11-10T12:13:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9uG/vun765dAQ//clvnX9bLy7x6fQ8z+gVZuawwBJ0akV2VVgo0kLQGHc+6
            uV3+jDLGX0XFZMw09N2urbTw5FubnGbLY7mcvYMUPElDuXbBu+QKx5NK45AsJvQ+
            1pN0rTpoQBSLnRLqBohedj0AJmlsHlQ75dakYPdS2Io0LFUE8ntxzOn0kcRCPAxY
            4QUQGzu+SAkL1nPAuZ+6Zq7uvIeqLmwif1zn0vJlFwNIO5pvLnPD3OVZGPKmMYFf
            wTRKTVhHPmRx6AAWztu13AhATfUkOSLreHE1lKhNtGmH47nLd4j2OB0IfNZ7/TDK
            Bs7io1wzUY7CuF64zRM3VPWeLgVtNJ5r4MVxuNZrcigp1xlrYy6WrpPJd6yeYnOZ
            MUCpNL4XKSAAtz2D/mKAQyjx+wz24MSLF8PJDmWQa7dLIYySxEGB9x4BW9XTadsM
            l7MAEZ+tDEp2OoS0cHIp7DCcus5zi05CGswdlUupseSfjBfWyHGMJ9J/Tki/U+ES
            yv7bDcltyPUArDprxuKOr47aSngG+lD5X8nIZzVaYQJiBS4xFU+UqDCQBJmja+E6
            DrmDx5FwDwrvWou3dIrcaFlOIDWJFC1KUoXtygZlrXUc2s2Ac1O7gSLPJz1k52oC
            SXVTac31Hp7T15Wsl3MdsIafG7Zes2Pab8S2up8Q0JKYoiFhIdMvGh8WmqLjReiF
            AgwDM/F2oUAwsAcBD/9VBU+zQiEYe95SzwHYnLwYXdagUJu/tihHKI8+nClY6Xri
            mAEfZP4FpWu+sUsM0au25BF24MMr3cQ4ut3FG1F/jzvZ/EZ+3ov/WCDuKMaVGJSF
            OAzQ7pnJfW1TtTX4/vwPkN2fnwAj7H255ef0S7sHfew/IuLodWaimBP5eqmuUOS7
            /M0POlNw+w1fFS6Us/rl74rx6LqIakPbIDAX7Sl6rfWdndnXAnk4A+qXpjAzi8Yq
            EWA0BqRnwbYyMF7L9nx61QVKdyWLDcjTRMD9ZGlYxR8GKpBOeWhNS2MadWi6gC7m
            8lZ3gwmenGEjoYL/40yDnhW6j8AV1ZW4CBpQ4GcfZuCZpwwSRMSK5WldyRojweOP
            JVZq4EEd6rz30AK8Y8UqeV88IHcEUXD3KJMvTjpQhmz/rvC7etmbSt7c88nUtigx
            wgh0hTXUMj/x3vyAtJhP27J/s8oSJguA3W8qWYI0+NEatOJ+Pc52mD991gHwQflr
            0wgUn0SrsA4QlcoEigS94bCwCY1YaxUQ4EgVUiW03H7NZEdRydCx8ZOJjUBamFV/
            1vpXEBaH/R2D0upGiWkP6SnFCUHEi2Gj+EgXav23XbMFOQG82Vqa75ixnGevxvY6
            UrPoVVkdISWRSl2iMOl/KPltPsOJVBon0gZE1Gfq7xRjUfUziOVqsR7nJ3OQpYUC
            DAOGLKZO92RuOQEP/jjwYPvzfHrBvxiJqI3YmnpEkhHqbn36avJZhOo5p7ww16AN
            JGx60p6f1XUEHUFGDH+WxQUBOmboQQv1w8KI2Ba7tI1/T4nxnY8RyACBXC4Q6bMB
            CUrFb98Y4SZN5IckYOGMq8qrf80WuNrBwcKvNBWOjejr798o4zP2kGRyyet0xKfp
            MgJgdk0Qs23J750QBwM09WESGJCbxXxBJsDvNvrzctSFgZ2Hx2wkDmS99ASagixj
            rijJIBjpBFT5THgiQFMcPPYN/E0SfTXxBNCTGaHV9Jzk94C6OACygLIsET5b3whL
            YUK0IhOe+qgcxNouM+YknlI9deTci1vEorP0DW4BzIVWj229Y4/XP1KKb+0VtGxP
            MYhZtfokx8DnmbXq9LMDKtJDCX7IjI5+cRzUhr6NV1n9V1cJxYsstlfV/UpyziqI
            phzdjqT1WxhOMqmLUC/61YpbhETk3OYq3DiJcz32QHzjx6XknEBzxXEDxaLMEbGq
            KZ2k2XFVXxUyZHdHV5BMQRlShAiAvyz6wUzGPkG+yrrr+IQTuXRTdMsPyaujpNoY
            CgtQIMJeWrvPYfx2tXtr032MitoWc0ew+7CoiW1C7RAEEbuA3Pmyg8MNQvsMVxGE
            9wIloNIU0WnpCFA06xkbv+Ejk9xeZ/hPw3HoH92X+nIyaStpfmNn+Sb9l+P20l4B
            UOtSaJsgzixIdpu+uaBEl4BLp1nU6VrIalHbMZ9T9LzHeyfwh2ZBOtW5vwAC9N+f
            QyMDa8yYc7xKGsiESsmGOKO893/mt19vzfW3ew5RSqNOZ8MnytoOSezbMeIP
            =ftUp
            -----END PGP MESSAGE-----
          fp: F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
