# IPAM mode
ipam:
  mode: kubernetes

# Kube-proxy replacement
kubeProxyReplacement: true

# Security context capabilities
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

# Cgroup configuration
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

# Kubernetes API server
k8sServiceHost: localhost
k8sServicePort: 7445

# Gateway API configuration
gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true

# L2 announcements for LoadBalancer services
l2announcements:
  enabled: true

# Network devices
devices: "eth+"

# Hubble observability
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
