apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - tailscale.yaml
configMapGenerator:
  - name: hass-config
    namespace: homeassistant
    files:
      - configuration.yaml
