---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-longhorn
  labels:
    recurring-job.longhorn.io/source: "enabled"
    recurring-job-group.longhorn.io/weekly-backup: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
