apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coredns-custom
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/configs/coredns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kube-system
  wait: true
