apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    solvers:
      - selector:
          dnsZones:
            - "prod.k8s.home.logikdev.fr"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    solvers:
      - selector:
          dnsZones:
            - "prod.k8s.home.logikdev.fr"
