- op: replace
  path: /spec/template/spec/volumes/8
  value:
    name: host-run-netns
    hostPath:
      path: /var/run/netns/
- op: replace
  path: /spec/template/spec/initContainers/0/command
  value:
    - "/usr/src/multus-cni/bin/install_multus"
    - "-d"
    - "/host/opt/cni/bin"
    - "-t"
    - "thick"
- op: add
  path: /spec/template/spec/initContainers/1
  value:
    - command:
        - /install-cni.sh
      image: ghcr.io/siderolabs/install-cni:v1.7.0 # adapt to your talos version
      name: install-cni
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /host/opt/cni/bin
          mountPropagation: Bidirectional
          name: cnibin
