---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - github.com/metallb/metallb/config/frr-k8s?ref=main
patches:
  - path: namespace-labels.yaml
