apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
spec:
  instances: 1
  bootstrap:
    recovery:
      source: source
      owner: authentik
      database: authentik
      secret:
        name: authentik-db-secrets
  storage:
    storageClass: longhorn
    size: 20Gi
  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: authentik-store
          serverName: authentik-init
