apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db
  namespace: vaultwarden
spec:
  instances: 2
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 15
  bootstrap:
    recovery:
      source: source
      owner: vaultwarden
      secret:
        name: vaultwarden-db-secrets
  storage:
    storageClass: longhorn-no-replicas
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  backup:
    volumeSnapshot:
      className: longhorn
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
       barmanObjectName: vaultwarden-store
       serverName: vaultwarden-1
  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: vaultwarden-store
          serverName: vaultwarden-init
