apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db
  namespace: vaultwarden
spec:
  instances: 3
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 15
  superuserSecret:
    name: postgres-creds
  bootstrap:
    recovery:
      source: minio
  storage:
    storageClass: longhorn-no-replicas
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  # longhorn snapshot
  backup:
    volumeSnapshot:
      className: longhorn
  # minio backups
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
       barmanObjectName: minio
       serverName: vaultwarden-db  # destination
  # recover from minio
  # externalClusters:
  #   - name: minio
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: minio
  #         serverName: vaultwarden-db-ter # source
