apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seedbox
resources:
  - deployment.yaml
  - wireguard-secret.yaml
  - pvc.yaml
  - service.yaml
commonLabels:
  app: qbittorrent
