apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - ../../base/vaultwarden
patches:
  - target:
      group: postgresql.cnpg.io
      version: "v1"
      kind: Cluster
      name: vaultwarden-db
    path: recovery-source.yaml
