apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-machine-learning-longhorn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
