apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  values:
    server:
      route:
        main:
          hostnames:
            - authentik.k8sd.home.logikdev.fr
