---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  values:
    operatorConfig:
      hostname: tailscale-operator-prod
