apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seedbox
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - tailscale.yaml
commonLabels:
  app: jellyfin
