apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-longhorn
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 800Gi
