apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseerr
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyseerr
                port:
                  number: 80
