apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: seedbox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-ultra
  resources:
    requests:
      storage: 1Gi