apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-minio-credentials
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:rd0gKmIR1cA4epE5eg4zdZfgtA==,iv:voFkRmxSpDjFX2eRD2GMtZ45WynI3N2oLDbd955GfEY=,tag:bw+ThohbccVZfKOf0mnwVQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zzbLEOVD+TV1+CQMoS2OV8VK3nWpQZOgDfXVbWWyO/4=,iv:5Bb2YlEvtjcXr/Kq43MDGMoa1FgpAQVGCaUAGr7GGnk=,tag:p9wWr6g9x/A98gRF5bOmkQ==,type:str]
sops:
    age:
        - recipient: age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bUdyMDR4NGtoUVQzUmhz
            NURvM0w4cHNTSXBKN2g5SGZiYkEzeWVJY2lBCkdYZUh6aGdpcUxFTU1rQ292RXRT
            NEJWTFFxTE9mVWpYMmhzOXJTUXZ4cUkKLS0tIE5GcjYrZGRsT25SaVBoZ2gwY1pB
            aG1QR3JYUjlsc1dhMFhPN0NiRVZVZjQKH8knqgRNk+kQ9VkNGrdZ4k4eErN8kDQ1
            UVByzVZp5condMButAx3tuuFFPGPsAONW+3EggbjYNx67wynHcWBqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T13:41:11Z"
    mac: ENC[AES256_GCM,data:CykGUqZoIMnHYSRgl7Qa/MO60jq2WLFTWc8IYnYNG8KmdCbgAW5PHVHc18BrXc5zGHxHJFe9Y8SwL8u0ZNHT986IOZj/NrI+0UiqivL1HXEd/eHnxshHoYCooLg/MPHSHVrX1gFZMF2la3xUp3RW3LWE332LqE4PEhqWOyRfYdk=,iv:qQRZrtD5MtXkPKZsaSqVgENfGeCCemHorHtuPK69UP4=,tag:W01gxX+OvyHhs2Dxvwvo7A==,type:str]
    pgp:
        - created_at: "2025-08-16T10:19:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9uG/vun765dARAAuvsBNEChP6yRr1f+ADO1/qWw7qGIqOr8c8ZqFKN3lGA1
            QKasetxVac4NZNdBoKU7ShgeiGLofnM061Ti0qn3j2dqTLJBVfoCYEnVdkEgEiuo
            0cBivAx8yl5loWoH/H4mlckpL3H10cVBZRxWivitJ4G47XNLf0qQdduTpIc6Fmz6
            kUTVE7ZfvmJoriXquGk/K+5fHZ6hG6DooyIWbFUORq0DhPIijCtNzxAljkSLgKEi
            23joe01Y1YIyMsl8IiCUh666IXBpC+bz+7bQVnXryFbJLAttShH54cXEzFBFDBMt
            RrSxlBu510WJsC9l6GqUtSK/NWR1ZItyNmIkXoxB9Bu4W3SFPQxCCHhGPbuElyXx
            yMPOxPXo60rfkmoZh3n6muGeVzH8lBM18F0dcs7KoikTG/ejnqLrDJPzcylK4EiJ
            EBZJbk3MLYlD1ByQxi9lO2oskBlUJtdx5/s03pFaV95L6RCoARFJ3drkmlL5PKQC
            dJiDPQg1JlZ3q6oD8AEvwmi3ct1mue72XxvZgtfKDpM1PdUZK5HD0O4w4OSOtPN4
            ARM70KSu8ylsNOJ2rtribmnepsUuwoAnYJWntTUinDyV1mDabAH62rG/UPcHUGAm
            pfFBVXRbjip/DzNX/mLP5k8lbiiJL/0H3rPMOHnPeR7FRciYgzzgaI4c1xHOSSqF
            AgwDM/F2oUAwsAcBEACp7OPb8mInX94A4OfCYPMGdQXVQw8BAKm9SqA8hSz+fQ/t
            jY1ZGxAUQc+wnKTq7slsb8XkCA3nflz9iWwgE7t2G/GAz7d66nmVXWN5HY/eO6pS
            FwVM77K65VYhSssLeVIFwu8IH8AozLAnBoTgirbAJxIeFZk5VZj58deglIJ/+fIZ
            +iJdR23xaky3SSba6/v5X1RTeqVmSYEsR2Y/JEWG/Q9M5vlBjkcACh9dlufQrH9X
            Z4NGPUI7/AWccIezmHmbh6lRE1FKvQg48n2hkgal7zxScf8486VaLIovZOxEU0tu
            27fyTDzR+5mAdjUQ977szDoQ2Si+fdsoa8ewScgTw7NDp4b8pd9u2npHoZjyKKqV
            zYOyz5zaoKYDH4yJtsyvlGrnfXqozLWzQxg3Yx884v5wEONZYFs+kAL42spmR6Gx
            arW8x+lAvWPep9oNhH7LSCWKcRzd/NLGq0Dct/3nultboGSTmCP8pwdu2PAb89DT
            /CdDjaJeqsTtYZUQ4mGLPMxecfgDk92GKTopYIkx3EUsf4PZUdWPs5JO+iWvRxOz
            kXHsaiSuNLNgSMmqIRf7TOKUI288F7/AhbA5beV/VhLIdPBFavEHv33vX9IgpmnO
            T9fQshqy+PH081Mn0J6qsTolyeZbC5OZ4QJb/2mFgxy97WGdnCK/MMX7bbqbm4UC
            DAOGLKZO92RuOQEQAIYysWOPwD12fJzfFGWAto6ULb9CBKT5ijMjbZU9TsT3NZXo
            CClHKVdw9bL9X1ZcJAFeteLOvbq83YIVb/cP0SdbwnDd53GqbmSf6gd+pELD/tIH
            CrdHHwASJub3AFw1ch+dk5kkGATXlPg93YfbA9ISyYgRlQqsEOIVgqvhyM2Q4UZe
            aHLm5omfbqmnYksxRn3h9mQJLlwVgjimwGdS6v3bDdkucDb/LoAChFom3F/piUbE
            dZhhM74NKKVQanBtq1iQskHaRTrF4pvIj1piWRXS8NvFKd62idxCVW7JyeYK9lti
            FPib/VdG2trqsWiH5Q1vZfKVOCdpQk8oMHiM9N1IIk3y9AabfhvnzvRkWWMT2q04
            Z28nyxd1g3KINmHv3qLo2AMTkQSkTXUuk3vX1HsEKZHIkr0lt78fvo9lKHb0oEBi
            5xODvhUc/bXdfJQgFKck6S90p2T3WQxvdvpD8RnXzmSDlSBV9LF1SI2sQk5FAxQJ
            /x/iKPp+F9NvnJpcfafIttQKCu1pG1YiqvNzL9fXi9y47duCDCivR/GgeJYc4v+L
            oeXx0eLonEHf4HX0pk2aFuXORW4J+NlfZ/DBuhAuBHFp93NwbovixWb/xNasCaIW
            NrjaRJVAW2ch7O3yHPTTVJ/Ws0Qkp5pXgoijiYneEDxqIFb1KI6WHy+GoTF30l4B
            dPMBVyKLqjXvnSmVAEMkhL3NkSgeU4khv6v2705RMfm5gKvz0Q+OA12qk7u2vNSk
            MIf+blPL3s9YTP1mBKuKHxfO6GGgHvh+a4R6273FJ/zQp9eYJwVojZkl2C6+
            =DYIU
            -----END PGP MESSAGE-----
          fp: F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
