---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn-local
provisioning:
  diskSelector:
    match: disk.dev_path == '/dev/vdc'
  minSize: 100GB
  grow: true
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn-ultra
provisioning:
  diskSelector:
    match: disk.dev_path == '/dev/vdb'
  minSize: 100GB
  grow: true
