apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: radarr-db
  namespace: seedbox
spec:
  instances: 3
  bootstrap:
    initdb:
      owner: radarr
      secret:
        name: radarr-db-secrets
    # recovery:
    #   owner: radarr
    #   source: source
  #superuserSecret:
    #name: postgres-creds
  storage:
    storageClass: longhorn-no-replicas
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  # backup
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: radarr-store
      serverName: radarr-init
  # restore
  # externalClusters:
  # - name: source
  #   plugin:
  #     name: barman-cloud.cloudnative-pg.io
  #     parameters:
  #       barmanObjectName: sonarr-store
  #       serverName: sonarr-init
# Radarr Main DB
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-main
  namespace: seedbox
spec:
  name: radarr-main
  owner: radarr
  cluster:
    name: radarr-db
---
# Radarr Logs DB
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-logs
  namespace: seedbox
spec:
  name: radarr-logs
  owner: radarr
  cluster:
    name: radarr-db

