apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: immich
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-imports
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-medias
  resources:
    requests:
      storage: 500Gi
