---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-monitoring
  namespace: longhorn-system
spec:
  dependsOn:
    - name: longhorn-base
      namespace: longhorn-system
    - name: kube-prometheus-stack
      namespace: monitoring
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.9.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 12h
  values:
    # Only enable monitoring components - inherit everything else from longhorn-base
    defaultSettings:
      defaultDataPath: "/var/mnt/longhorn"
    metrics:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack