apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-base
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.9.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 12h
  values:
    defaultSettings:
      defaultDataPath: "/var/mnt/longhorn"
    defaultBackupStore:
      backupTarget: s3://s3.logikdev.fr/longhorn
      backupTargetCredentialSecret: longhorn-minio-credentials
      pollInterval: 180
    # Disable monitoring for initial deployment to avoid circular dependency
    metrics:
      serviceMonitor:
        enabled: false
      
