apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr
  namespace: seedbox
data:
  # AUTH MUST BE DISABLED ON FIRST INIT
  #RADARR__AUTH__REQUIRED: Enabled
  #RADARR__AUTH__METHOD: Forms
  RADARR__POSTGRES__HOST: radarr-db-rw
  RADARR__POSTGRES__PORT: "5432"
  RADARR__POSTGRES__USER: radarr
  RADARR__POSTGRES__MAINDB: radarr-main
  RADARR__POSTGRES__LOGDB: radarr-logs
