apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-longhorn
  namespace: seedbox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi