---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../base/traefik
patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
    path: gateway-hostname.yaml
