---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-crds
  namespace: cert-manager
spec:
  interval: 24h
  timeout: 10m
  chart:
    spec:
      chart: cert-manager 
      version: '1.17'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      interval: 24h
  values:
    # Only install CRDs, no actual cert-manager components
    installCRDs: true
    replicaCount: 0
    webhook:
      enabled: false
    cainjector:
      enabled: false
    startupapicheck:
      enabled: false