apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarr
data:
  SONARR__AUTH__METHOD: External
  SONARR__POSTGRES__HOST: sonarr-db-rw
  SONARR__POSTGRES__PORT: "5432"
  SONARR__POSTGRES__USER: sonarr
  SONARR__POSTGRES__MAINDB: sonarr-main
  SONARR__POSTGRES__LOGDB: sonarr-logs
