apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-assets
  labels:
    recurring-job.longhorn.io/source: "enabled"
    recurring-job-group.longhorn.io/apps: "enabled"
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
