apiVersion: v1
kind: Secret
metadata:
    name: sonarr
    namespace: seedbox
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:hJFCV+AXpJ4z5jwwYczVw+ew5nxWEVDYFFFVVEo2z28=,iv:QAMnp/Oqw28LJpqh3GxNKK5oAlSsGpARn3lgiyNQjXg=,tag:p8FIVenHY0VM8QPDMTgWXw==,type:str]
sops:
    age:
        - recipient: age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YXdvODZRZGNwcWY0S3BP
            OGRYL1ZRQi81eGc3WFJHaEJCZWpmRTl1YW5rClZzUTl0VmwvTlEzbTJyaURjSjRQ
            VmgwNWNndis1UE9sdWM1anVvbUpabjAKLS0tIHpyaEJJbkVWZS9pM1hoNjhNeHlu
            dXRZZ0VISUJzUVZBdXFRbHZmckQxQk0Ky95yHw4u059ZWI/pMoJ7jrL/jNgSX2ee
            zigwGSWTC2d//5oiLhsvkhiBvN6LhpKwP7SAfyvx/nUuaZV/uzPkAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-13T16:57:13Z"
    mac: ENC[AES256_GCM,data:Edd+swIuB+RVNjl7fm0BgcwPL1wki85II+a6qFvzYY15Wmoo2xW1kveoS98vTf6mmpPfszZE0ytq8cZSsj8E91sPs3DLkk2TUIz/AeLllzqBAMW+02MbJpQmmrZnoeNZqBkJjQRZyrbmst2gv6f8cq0U+2XpcBFC5cfNfYd2iS4=,iv:oyqZ41iiPpSFrAI+Aat/A+VDXKU6RPkSCJSHK7f+LLU=,tag:EJHZiEbWHceSRnb0PjwLTw==,type:str]
    pgp:
        - created_at: "2025-08-13T16:08:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9uG/vun765dARAAlYcEpi4UxrZiL9R6asG0Hy64yhTBNGIjy/qiXEEsgYkV
            6nPlJH/we3spz6liceakeDhyxQlDvxKQpd0naqzKBaqeGk93g0oZKvbggdQHa0H6
            1tppD33855sj0n0FUmoQ3cya/LQUmUx9zm/MRulm5w6QIr8FUEkZ4GIOMt+1PfEt
            yIE1Oo0YaOmuB10yBkbM1++x1OxB8Z0rZywM7bmZ5t8pMyKbFSrdfxnpT57Oyvf2
            53UDjbGXBl03PmTpxBezKfX9FODh0eDu3LVqszBgI6OPD7tP64TM2pYep21Dxnqz
            GuOrVKBDKGSIHBquJmPHRm+hxANcpldp/swhsCZc0hRsRPMUZVTZ64ia4ndpBgQ/
            vwIfs4tVDWhzXcpjU5DIAR8fZqMRDTOTyGLJXSh6TwsVR7GynxcI1DiLMou+ZHPo
            1fP196pMDn4WBDh6A8i9t+d9NHLRJKQpjSsaF0AvQPxrsDbV6syqKsQKJj9lKgN3
            EOWfrTp+YyinNNzDWGeuciJVewNMO43rVea7tibh021nBP56kHyxS4R/3BFlElQ1
            11ovGh72Ny0rcP08lHQLS3sVK3b3RSeI/L6/VGgMu+C/lzW/qFR6UXKFLnEZ6qpG
            eRKKPYLZ/xconnu/MTjP+OjGAVcQ4LNC/VAtX15iPPOIiYnhzx+uU7BObeiDvQaF
            AgwDM/F2oUAwsAcBD/0YQ7JLx6RGFlggopElkhpHkeR9Uu4+puNIfo1qtpkLjIlm
            PoHYojv/NTVncmLydhbjrRL5UH6dUHH1xuQ5ZyvBPDRkm4En5wa6UVaULRcYzEwk
            9NYskf4c7o9NbNzIxcGdkjUZMX1fF4hvnNIXJJDMhYO2JIroksD0F7kQnxKq4/0+
            1d+Ljj0OKb7tmOb8LNh4dq6+nMgY6/NPnr6mhrlhuUvwApqQi3tQfxrOz4SVw3ur
            aTBjPZmFCRZB3m9GifT2h2zM0SKZiljfR8Hfy2peRf/VtW0Zv2fX4EWFephc759L
            qVpy0iEOOp+B2nrpSo4YJ9H7EyG1qXghGNv/hf6zjTk23fIxeoe/3yZ2cIxBr2TZ
            cyoGCD+ao0bKOgyEynaiHxJhj6l/gbNioEboziBBFNS3Mzdy7gJYXUUkVbnZAL+Q
            OyzGxxB6fakUpc0aonnl8OnSr7FsohkcYMfNpXK76W6TIKXnRxpqAfuOtqWfrmeR
            xB907Hcmt7EX46H4EDOg5X4VrjHG2hbXqgyB7PJZ/l+r2pu0AbPF7RpOwb1rICqI
            Vrd+GKwLXhgLkd8eybTeisKsWFPs1q34rqpo66U65VJiU84a7PGz9A8LrAIsPixY
            GsjyyVqueMJf2Qov2QHMLISVWsJs01Xdpf2sNyLv3aZ44SuPzTnyZJnVVZxmsoUC
            DAOGLKZO92RuOQEP+wZWH8wJU32sB2Ds3uaI1o5z5sVBCpSG9JFLwPgWxDLrUVKx
            q420AhLD4+L89imj25/sZye6hkIviTXLlUAxiGtVAapSw4X/02X1gL3DGIxGhGiw
            7hm/aBWA6Kgg1OPJMozLv8ytd7gFkkcUfuqP5ub8z6lWnKEnN1PHRECwmY7sW+nt
            KUWF+v5/v3s1Z/ZN4EzNleRwBfEy8dVFsMnGTUr3+awJppCHt+BY9XMjPBDql4sa
            IaWM944VSRwlVVPaLENIN6lQZ9J4VoOxv8QeJcNKScJi4Qb7/ykNRWo6/ch8iLcF
            ZDYetXKPUym3VbnEPhq0k5ZVIGOZg0381JNtsHW8PHGD7eP4URs+K6iuJehQs9tJ
            8cRyXkhTl8UUfhOPWul/KXxn9Z0REO1o/HKtEwnCIOFOFIqbF7X/invq/EB4J4fK
            jQKkY3Z8gC6cP+FW1RcjzXma+YiiBYg8fFuju5csYfS/KWDYuHHL093nUh1w32eC
            CeucNx55ULdy/WlI4o4af7EKM8tq3iaQdeQuKF4rTZAOwCzh1K68fA/oV5VCYTf4
            U4WpEkcDRfVQq5r1zstKF8NRwK8ls59hvvb50Y1TCtM2YkgdbH/bZvraBpcNKugG
            aYznPfpuYxj263jC+rjVheFW3bZxiunMGkirFdXjWJTwwCPqSXWOoNBtvCe30lwB
            hKilMf3SsdMohtxqOLGLTdjUa2xBr8/2zWr2y+o2WTeyXFd+8IJcVqETQ22PVlCW
            aMnfB455lMLd6PBZWWCCuAotWaM4FvrIe1O+WuDbd8I+NbtzmXsbwBSBUw==
            =qQN2
            -----END PGP MESSAGE-----
          fp: F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
