apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 2
  bootstrap:
    initdb:
      owner: authentik
      database: authentik
      secret:
        name: authentik-db-secrets.yaml
  storage:
    storageClass: longhorn-no-replicas
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  backup:
    volumeSnapshot:
      className: longhorn
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
       barmanObjectName: authentik-store
       serverName: authentik-init
