apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: "0.16.2"
      sourceRef:
        kind: HelmRepository
        name: nvidia-device-plugin
      interval: 15m
  values:
    runtimeClassName: nvidia
    config:
      map:
        config: |
          version: v1
          sharing:
            timeSlicing:
              resources:
              - name: nvidia.com/gpu
                replicas: 10
