apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: sonarr-daily-backup
  namespace: seedbox
spec:
  immediate: true
  schedule: "0 0 0 * * *"  # At midnight
  backupOwnerReference: self
  cluster:
    name: sonarr-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
