apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 17.9.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: redis
  values:
    architecture: standalone
    
    auth:
      enabled: true
      existingSecret: redis-auth
      existingSecretPasswordKey: password
    
    master:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 8Gi
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m
    
    metrics:
      enabled: true
