apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: radarr-db
  namespace: seedbox
spec:
  instances: 2
  bootstrap:
    recovery:
      owner: radarr
      source: source
      secret:
        name: radarr-db-secrets
  storage:
    storageClass: longhorn-no-replicas
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: radarr-store
      serverName: radarr-2
  externalClusters:
  - name: source
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: radarr-store
        serverName: radarr-1
# Radarr Main DB
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-main
  namespace: seedbox
spec:
  name: radarr-main
  owner: radarr
  cluster:
    name: radarr-db
---
# Radarr Logs DB
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-logs
  namespace: seedbox
spec:
  name: radarr-logs
  owner: radarr
  cluster:
    name: radarr-db

