apiVersion: v1
kind: Secret
metadata:
    name: radarr-db-secrets
    namespace: seedbox
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:d0DdnXk/,iv:YWrT4+ivWO8iWbPybwwbAU1iOiKoOoh9kRAwv5SjXic=,tag:BM/HHyCNHACT9fP550khsA==,type:str]
    password: ENC[AES256_GCM,data:R7h4FFE3RoBRJHnTnT9k8vjUcaQyn+P3MB+SVNWJlpGLgI0CZQIIIrozyiiBB6UTQEw=,iv:SW0bQp0Fj7BDe6uEtc6cyRO7i/d0nj2OgMPiWfYgQSg=,tag:y9HaJOlqNDBbgfDwV6pdNA==,type:str]
sops:
    age:
        - recipient: age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVEJhTlFIeWtQNU0xUGt2
            L3ZEbnZtZDFyRnViMFNTcGlqWFJCc2hSMVYwCjBXRzFaOXVyUXVzRGw3OFBwMWdv
            SS94MGZxdjF6ZnQ5VTNwYzFCZXl1TXMKLS0tIDhJQ1hqWllkTkMrRDR4SFlBcEZi
            Qm1vOXpCWWo0aXYrZTFpRk9jclM5azQKi4rO1gPoCtFgMyimAL8KdXqELUiJXVbl
            PXce2XzQkA7f1FnxNUdrIWIiEUUd0WwpxMOFhmjNRim4BatD16K9IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-14T09:53:42Z"
    mac: ENC[AES256_GCM,data:saNpdTwOXoSCcz1qmVzJ4oNUsrkAkUVoVXnkkQ28HEqGW5j39WnrnA5JUpgKnT3SrQHGHlLfo/d1cXpa2gfH4Mztab+6xYhM6htXOFWzJZNVO6GUQA8F8NBntDXryqY9CIXaDpfBQRaWY0197nnFB6lP0OkUajIZb4jaxL43slw=,iv:jDYGGbRod9EJcGUc3sQdEmzwUeA3yIVK3HZA/JBop+M=,tag:KCR+KeJRBoYYRcDpquJJUQ==,type:str]
    pgp:
        - created_at: "2025-08-14T09:51:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9uG/vun765dARAAtFJnDOXZ43k6Tq9XkgsS+U4OCZOqWvI5Z6I1p/l0GP5+
            VVErtIffRbXLRAhAgga0IrCa8J9c1gUtGaaGnGCTIIh9WauBJNs7d0Bl42ZzS4p7
            q5E/ot2T+D6p3NqE4BIlOUpyJ4Wpzk10frhVUiCYh6CBjJAMQrS7WToGhK290PyA
            nOYJu4jNY8TOuv3AN0cLei9sQcNBehUp2weGemCx8/fyPvhGKhCfJwo4tixs6GLf
            ZEA2ioYX9hJFpOAqfj8+6QvA08Y9+D+gRXjhCSHp8Na4ISkHvxkjwy2jorbeasY3
            ZsBkblaDlA0Hxn1O87pVP6koCQbXW4RyaEowMlkoDqne2izjJJ0Hya+jiWR+5pz5
            REhVbWeDTOyk8n9ri3o2o8PQOjuj4FADO5IlpiiqcsAhppHdXYvn9cTuwZq9igWl
            /dONK9iv9XbdRCbfuPfFNuuhMlWCb1UyhfgfAc43MKc+d9jRklgS+ckW1QJnTz2T
            A0cw8cli8Ixn2qgEN/bctv0RhZB+oitxxISuwSeCT+FxUidUdS7hi7o6meJQXUU7
            HVB2nq2to/Ra+sMI/rXlEb1DZGMyG/e3JKsOZ3I0PCIlnSeXCfKFw77KizYvzbS7
            WAADOe3FVNfoTR1VdNRPh3FA0vRmPcqYK4vcgUaSIiJS33hUAF9TZfSP9hhUmLeF
            AgwDM/F2oUAwsAcBEACln6HAhKeuodaGzDPIyMv16QUhKXMQOIgfQuiNazYaVQNo
            po4VYAygAfgVpqRkedFshq38VUTYl2vlvpWDhekh77AD1qPLL9UwP6kC/KKxifbT
            SrEAngCLrxuKUBEj4bgtspBUZJwiiqsAIohVosOlzd3LGT+7o5n0iJa5/ZtlwglB
            DSaF9Rkr5QzJ9RoLHL5F+pFz2Jgf9K4aVvs15dlLNsINptiMPc4rHAkJuOyiH06z
            OLJpocYZpXTWg6a3zqUkAwlO9Sxxgp8gU4NDrqFQtJGuzqtJ3DhaB1miTI7WQAxl
            Sjk636sOnjH/YrLrMJQlegj2o8WFSAkb5yWfVtqaWJR6x5iPHMziSUCfr8psh45x
            L6BkJ2Fum1uOLGb+CbWIghKUoy8/MfaywMOKlsw3YtaGQJYu9RDxV9WlMTaK3x9k
            YC/aoqt20taHx3Xa4qFiz1e2Dm/55J72kQSFoPT8xW5fKE0TKsJ8xFcPqnYKxafF
            Cl780yviYkHidty/6Rk+kos3iZclgrnWyElYWWO+ysf3l8oKPVSE8ZYT4I+UiHDn
            YcG76ScmncAZhH7cd5nP7H0PqP32qmotEG91osbQzWzQRqsdjOCLdHT6DMJBHlCI
            inJvfe15J6QBZoOs1cHg4FYTEmcqDYsUAPAhHWHGxBtiVTnrXjgUW/f4jgxK3IUC
            DAOGLKZO92RuOQEP/1q567DumyeJAjZKH4g9ax8BVp26/SHyOHQix1vfw9Rqk3CT
            U+5nssM36l5FyNeF4Fh/gGdzDsUYTgDkl8pMsUuoyLUw7ROUxp8VTWB2NwE62AO4
            ZrBQaSKcrztMco1DU9mwdAezftzVW8/egsxew47Bq6SfnjRuagRQ1IvVrQYH86p1
            1WQDEkDmXuL/son5tjwDTWm74wEGVTqFrSfS6GaH0swrqkLIdNefZglD2YcDZLyn
            iLXWtnmuOWwgFEiSPq9VKoL4Utt0bek+mhH69F1MCoKMuuvzwOzuCk7V7rtrlX9n
            mE/lanT/fKparDz+ENsQoyvHlMDpmPrQj8XvP10vOkf04KlTERKvyEqoyDaAlBLR
            Y7jm46ib1PahpQ0jczpGzSIIOM3ZHcXK8SPPvU0iPHmYvHR2RDtQJN29zaKqyTKo
            Ndcret/TwfTxr5v1ov06hzrNw0ywHOueX6xwWIpWiRADwI9pwwgpHUG78Fl4qurG
            xnTuSgAS1Wg5mXeBxXzMAOh8cLYCD/l5DTxYcA4/U2wYQO3xcR4krRE+XC3Zijk2
            5D4FZwvA1bwSvRjuS7jq603s07hF1Q+jhtaq/U8Z9vVoitc/klo6byOXIpLJfG50
            RK8G2AydV4FquvViBlj7/0R6TZS2qNy4V08h+mkY32eYOZ968JhShPafE4Qt0l4B
            k23chWUtegtcNib6l74S/Tx2zggTHbmGqGtiDgmAPDLMRUKcocr+uKEY4emd9Pw4
            FTsUy5YtK4C69m6K0I4SR3Y7Cim6iEBO/mxNMV+XIiq/5uZdNRU3b9C4Efgf
            =iVM/
            -----END PGP MESSAGE-----
          fp: F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
