apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 24h
  chart:
    spec:
      chart: traefik
      version: "37.1.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
      interval: 24h
  values:
    gateway:
      enabled: false
    ingressClass:
      enabled: false
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
        experimentalChannel: false
    ports:
      websecure:
        port: 443
