agekey: ENC[AES256_GCM,data:eN/ZP7klIdU+K7l9tjj2mlHVP3FipCxPaiFr5v2GbOfbsn2KU15Hm9OtEONnbv6uoR+XwsphkSAgVfZaEWEkUl8eWQtGDGhBdiw=,iv:aMYEbuH2Tszq9BNB4F86b+oTno5vtzf+pjwmKB9my00=,tag:WD/JUucJ4HzLCzde4YooCA==,type:str]
github-token: ENC[AES256_GCM,data:Wzer55j+JM3LQud+qgELJj6yy+Ufv1S8aKk2Y/tp/nZubFG2tXhaHg==,iv:AZLcEqBUU/WEyzOOQ5NA7XHwNkKzAFVhsfPrmWVsnNU=,tag:bMeUEJP/QbrT1VIcruncMw==,type:str]
sops:
    age:
        - recipient: age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZGdwakJXWjZ6M1ZaTjZo
            cU1qWmIrL3VTYjVNc1JFU3o5dTkxK2hsYUNjCkVIOEZlMWNycDU0c3pPQlh2NWw1
            dDZ3MzM0VFBHUkN4dDltak9uL3kxdlkKLS0tIEREWjl1YkxwRTdlZldBN3pTN0xa
            dGpwOFhXNnZHZHptMVE0bFV5MEVrTWsK0VJPNm990JDF4Ofb18uxsvfr/5SC6vQV
            GRUTAizTJX0SAqoHY/hx38klY+fzdxC1Xgl/hZvggdqC5OyTpTmq/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-12T15:46:46Z"
    mac: ENC[AES256_GCM,data:6e8BFnxN/ZrvwylWICMvwzoG2cjRDQQqsRwedhIddPvzULzSt0eAJ5QQSGL7QvNfaaQQWaE+Zr5kgwt26gRKHJ5SZLwENyJpUR0ruXWE4L2Xtx7F/hezw+b6iazgDX1cGB2YSrTkn6LLEDQfsHyXVmAHB7+NEy71fcv5bWWpw10=,iv:j5s/Ti2vsuacvwpzanMiHoRNcTMRXhGLPxsTWaQjxvE=,tag:jmtSGWiK1eKDiGUSYmI9BA==,type:str]
    pgp:
        - created_at: "2025-09-11T18:46:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9uG/vun765dARAAiz9fGQrLxH+J/R+80cAMvl1N9GpoXdwX7dSEENdEH+VE
            quoEL/Yp6W/mqudnH//CVIRTJWcyNyJyHyjZnFAc+wX/ocxlfJ16S1Do9UQPqlZb
            Yi95Em9E8cEMq1kvL80XPB4TSctpKj/2dSJHVTSLMfmpN+84eAFNujUldVkzyPw6
            NCqmaHmvpg6+/cmFtCgkj/nuqsngX6KHM2bOAsDgdXmzQ85FOEhm9412Qpxt+5cy
            gtj0nSw0QfSBD9qUrxOXF+PQe2N3h8VZOtyPPGqbD4EP2uOPuUmhWVd0wYeUfwMA
            E8eFs52vWdtqPSgh0UnoMbFkdZYj/4swQEf8HKV3TjsCi/Zt66/UQ06ScKHo5pKl
            s5qIVnH9c48Sn3bqdAymRlHXv+qXL/j1nUJDY8sH5Xvow2CFxFFWOUq5GGCSM65j
            YG4+VKdx4rI3YzhI+pxBp6HLLemImHe/eIfq1SuX48T0QVKneb1+Nz5cZPgGN0XA
            UnOv3UnAhFH4ptcprxSCRyIyoQM9TVM5oZUqmkP45sY2CCB+Wuw8nbCCYxW5T7YD
            sunjujHwYNErGx8Lj2Neney5o0tsxvJomD+Q/W2aX4eM5U/gbh/tcdFHaOfTS/GS
            Gg5Bs2e8AtdZZ3PKVM4YSSo4BH4mcSONxlZONyO5TThY2Gb7pRrhAGXAwl1KLr+F
            AgwDM/F2oUAwsAcBEAC0Orr+BHY+Qbpsl+oAfH1tvR31Qpi9tNrgH9WNNrG8k4aT
            WnOfXmi1kJF4j4xyjhGXUXilKJ+4niWryPJ7jgz9Lbvps3N/w3nDVakUHzW4HWnO
            g7cRrf7q0D+Jc8q43NIssV+/yiaTD8ceoEtSygL9dp7HD1roIGc7YP+6fBudwDce
            AQeNux0CwPgvSi7Omrwr9ZtL7Ar9dtUzyJbsSKyrJI4pd75JkNWOJcGQ7obdsIRl
            aNNwOv9viF5qed6fmXCEtO9Fl1gTzDvlP7JK8tvSly5Pt57IU5fMPUzPHBErcAPq
            0t2D1DCeW5/G66w/Y2AGY9utG/XpXpJRbnW3wP68oFyc8DvRbRhQB4Zt7zDy6Qt9
            uvM01xygfhxY/K9jijq9Iv+0wVXUYcfeqAQyF/5lFzLfkSRKmn7cGnwZJaKV9UfD
            p3CdMSMLEZbAZjxtOj/WLOGvZp6xugLmsEaRlq2nYqp+lHDukqY/QOM6ekyvp8Up
            nI2qRf16zkfDiXJxbjobdGuqffCx8r3rKUiRmWnCeL0oPoWGTNqLM45cLB22yO6R
            CBIWBxxTEJyOZm1jY0PlijgVyrsLnFrrpLTmhD3KU1Don/Eu7o/7uK/d9lXrogNh
            G1UaPENIjvfiUdAZ6X4m1PrEZ9ekJSF+cPKFl3bQpoUeqplNG8Jf1BfrTcrLE4UC
            DAOGLKZO92RuOQEQAISCi/PEoAGEVUlGaVGERte5/gD/VHyOmEcBFxx8+KKNUcEc
            kklHNO3Nyi0WtzC/NdWHw51uk71zHtJjVxUTkAZx7Zx7kphrTVMygdaeJkHbA+qA
            1sj0tByibJPg9Y3qJgeXd7TDILluypWo6tWEiSfKpaPYMDyN9Co0uc0gNPk81T2C
            5rsowHQvb7ydeeDxldkz63WrJB0ykSmihpEBToKHj9kKSw/AwSe4lJSfX8zvXWWo
            xB2gruHpJu8+JII+d6K8niwru/t/Aw44dKnMVFOQeDvbFaSgEZ7SijLaSuVAPhWQ
            lMqog6fXSu26FTq3N6WT61C9B/U7JJN7hz9Den3H9beCA8B0Zh1wbJtL11ymvqG9
            WIcfO2+ZRQCDhcBmx6HON/qmVFUGbvA8uvnwBEkJbVzgGxizhIbH22uBHj0Msb44
            pOZaAtvW5+o8w0aG0x7x8RpHZNUqYMVCbuta6sQ8zl/RDunIRmF7SLSLLbnSwCBn
            feBv7ut6D1SQc+kokl9AGrzj8VZX3y1Tvg0cD2IuFAKaIx2jcaqQ6Cs5jo8o98Be
            P36vRj0pvWLJTUfMyxsj6ssxLicRvR0eorcThML+EqbRbISD4XhfkVD7HW9fZlKF
            GneqEBKc4kJPcjxcUjtD1CIqOVH0n0x0OjXW4+VsaLosveGXFLYlKGwElRGZ0l4B
            pjfea6NrAvSCmzmvd8tFjTGcJJrYn9sM5SjC5DUo7EbOvdaQtx/oDFApNw0tOH78
            cn65m/C7e6/lREDLJP2VkiFBDp5xh82VenUcYLvUl8XV3S1xc5Vi4VtF0YVz
            =+XMc
            -----END PGP MESSAGE-----
          fp: F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
    unencrypted_suffix: _unencrypted
    version: 3.10.2
