apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seedbox
resources:
  - database
  - configmap.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
commonLabels:
  app: radarr
