apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-imports
  namespace: immich
  labels:
    recurring-job.longhorn.io/source: "enabled"
    recurring-job-group.longhorn.io/imports: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-no-replicas
  resources:
    requests:
      storage: 400Gi
