---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-db-backup
  namespace: immich
spec:
  immediate: true
  schedule: "@weekly"
  backupOwnerReference: self
  cluster:
    name: immich-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-db-snapshot
  namespace: immich
spec:
  immediate: true
  schedule: "@daily"
  backupOwnerReference: self
  cluster:
    name: immich-db
  method: volumeSnapshot
