apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: immich
spec:
  instances: 2
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-credentials
  storage:
    size: 20Gi
    storageClass: longhorn-no-replicas
  backup:
    volumeSnapshot:
      className: longhorn
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
  namespace: immich
spec:
  name: immich
  owner: immich
  cluster:
    name: immich-db
  extensions:
    - name: vector
    - name: earthdistance
    - name: cube
