---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tailscale-controllers
  namespace: flux-system
resources:
  - ../../base/tailscale
  - secrets.yaml
patches:
  - path: operator-name.yaml
